### PR TITLE
avoid NonExistentTimeError in get_clearsky_tamb()

### PR DESCRIPTION
**Pull request by mdeceglie**
Fix for #372 
- [x] Code changes are covered by tests
- [x] Code changes have been evaluated for compatibility/integration with TrendAnalysis
- [x] New functions added to `__init__.py`
- [x] API.rst is up to date, along with other sphinx docs pages
- [x] Example notebooks are rerun and differences in results scrutinized
- [x] Updated changelog

### CODE REVIEW

**Comment by mdeceglie** [comment]
@BernatNicolau thanks for your help in identifying and isolating this bug. If you'd like your name to appear next to your github handle under "contributors" for this update, please let me know what your full name is. Thanks!

**Comment by BernatNicolau** [comment]
> @BernatNicolau thanks for your help in identifying and isolating this bug. If you'd like your name to appear next to your github handle under "contributors" for this update, please let me know what your full name is. Thanks!

Thank you for fixing it. My name is Bernat Nicolau and it would be great to appear in contributors!

**Comment by kandersolar** [comment]
What a fun timezone bug :P

This fix seems reasonable to me.  But I think we should consider not using the local time zone for the daily time series at all.  In addition to causing the weird issue @BernatNicolau noticed, I suspect it's to blame for the following undesirable behavior, where you get different temperatures for equivalent timestamps with different time zones: 

```python
In [1]: import rdtools
   ...: import pandas as pd
   ...:
   ...: times_utc = pd.date_range('2019-01-01', freq='h', periods=3, tz='UTC')
   ...: times_est = times_utc.tz_convert('Etc/GMT+5')
   ...:
   ...: latitude = 40
   ...: longitude = -80
   ...:
   ...: df = pd.DataFrame({
   ...:     'tamb_utc': rdtools.get_clearsky_tamb(times_utc, latitude, longitude),
   ...:     'tamb_est': rdtools.get_clearsky_tamb(times_est, latitude, longitude).tz_convert('UTC'),
   ...: })
   ...:
   ...: df
Out[1]:
                           tamb_utc  tamb_est
2019-01-01 00:00:00+00:00 -1.516891 -1.499855
2019-01-01 01:00:00+00:00 -1.863861 -1.846259
2019-01-01 02:00:00+00:00 -2.280853 -2.262572
```

Maybe it would make more sense to do all the calculations in UTC and just convert results to the input timezone at the end.

**Comment by mdeceglie** [comment]
Thanks for taking a look at this @kandersolar. I think it will be a bit of a project to trace the logic through and make sure that doing all the calculations in UTC doesn't affect the original intent of the model. The model uses the hour of the day to construct the the temperature signal, and it makes sense for that hour of the day to be local. 

Unless you have a solution ready to go, how would you feel about proceeding with this fix for now and opening your suggestion as an issue?

**Comment by mdeceglie** [comment]
I also note that the docstring asks for the times in local time, so passing UTC times is a bit of an off-label use 😃

**Comment by kandersolar** [comment]
> Unless you have a solution ready to go, how would you feel about proceeding with this fix for now and opening your suggestion as an issue?

Sure!

> I also note that the docstring asks for the times in local time, so passing UTC times is a bit of an off-label use 😃

Good point!  Perhaps much ado about nothing, then.  I leave it to you whether an issue is warranted.

**Pull request merged**
