### PR TITLE
Update master for release

### PR DESCRIPTION
**Pull request by mdeceglie**
This incorporates changes that address issues: #67, #61, #59, #57, #56 as well as:
- improvements/typo fixes to docstrings
- Fixes error in check for two years of data in `degradation_year_on_year`
- Improves the calculations underlying `irradiance_rescale`

All changes have ben through review when incorporated into the `development` branch. The purpose of this PR is to check that this version of rdtools installs and runs correctly.

For me, it passes everything in the [release procedure](https://github.com/NREL/rdtools/wiki/Release-procedure), with the exception of the minimum requirement check on windows, but failure was due to problems building old versions of some requirements.

### CODE REVIEW

**Comment by cdeline** [comment]
I get installation errors in new environments of Python 2.7 and Python 3.6 with my Win10 machine.  When installed into my existing environment, there are no errors.

Python 2.7: 
from numpy.distutils.misc_util import get_info
   ModuleNotFoundError: No module named 'numpy'

Python 3.6:
from numpy.distutils.misc_util import get_info
   ImportError: No module named numpy.distutils.misc_util

This appears to be a known bug with statsmodels for Windows 10 machines:

https://github.com/statsmodels/statsmodels/issues/3207

https://stackoverflow.com/questions/45492810/statsmodels-installation-no-module-named-numpy-distutils-msvccompiler-in-num

image

image

**Comment by cdeline** [comment]
Update:  if I use 'conda install statsmodels' followed by 'pip install .' to install the development branch, then everything works in py2.7 and py3.6.  Is there any way to install statsmodels through conda rather than pip in our setup.py file?

**Comment by mdeceglie** [comment]
@cdeline I was able to recreate this in a clean environment with only `pip` and `python`. However, I suggest we can proceed without directly addressing this. If a user has installed the anaconda python distribution (that's the most likely way they would get the `conda` package manager), they will already have `statsmodels` installed. If they are setting up environments, hopefully they have enough experience to navigate the requirements gymnastics.

We could add a note in the readme encouraging people to install requirements by hand if they run into trouble. Do you think that would help?

**Comment by cdeline** [comment]
OK, I'm good with this approach.  If you could include an extra line in the readme about manually installing components using conda if they get errors during install, I'm fine with this.
I suspect that we'd still have installation issues if someone has a fresh non-Anaconda python distribution and just tries 'pip install rdtools',  We don't specifically require Anaconda in the readme anywhere.

**Comment by mdeceglie** [comment]
Thanks for the input everyone!

**Pull request merged**
