### PR TITLE
Release/2.0.5

### PR DESCRIPTION
**Pull request by mdeceglie**
This proposed patch release includes:
- Flake8 code style testing in CI
- Reorganization of some pytest fixtures and a testing bug fix
- Add formal support and testing for python 3.9
- Organized example notebooks in a gallery
- Update `requirements.txt` to include versions of packages with wheels available for python 3.6-3.9

PR checklist:
- [x] Code changes are covered by tests
-  ~New functions added to `__init__.py`~
- [x] API.rst is up to date, along with other sphinx docs pages
- [x] Example notebooks are rerun and differences in results scrutinized
- [x] Updated changelog

### CODE REVIEW

**Comment by mdeceglie** [comment]
I will give all these changes a once over together here, rerun the notebooks, finalize the changelog and comment here when ready for final approval.

**Comment by mdeceglie** [comment]
I think this is good to go. 

Last to do item is to update the release date once we have the reviews complete.

**Review by kanderso-nrel — APPROVED** [review]
LGTM, pending the changelog date.  Thanks!

**Review by cdeline — APPROVED** [review]
Tests are passing, notebooks look good to me.  Approved.

**Pull request merged**
