### PR TITLE
add the logo to documentation home page

### PR DESCRIPTION
**Pull request by kanderso-nrel**
Comments:
- This uses the horizontal version
- Generally it's good to reduce the image dimensions to save bandwidth if it's not going to be displayed at full res, but the full image is only 330KB so I didn't do that here.
- Sphinx allows a logo at the top of the sidebar too ([example](https://docs.blender.org/manual/en/latest/)), so we could put the logo there in addition to/instead of where it currently is on the home page.

Looks like this when I build locally:

image

### CODE REVIEW

**Comment by mdeceglie** [comment]
I think that looks great. Good to leave it higher resolution, that way if people grab it from here for presentations etc. better chance it will look good.

I could be convinced either way on the sidebar.

**Comment by mdeceglie** [comment]
LGTM, shall we go ahead and merge @kanderso-nrel ?

**Comment by kanderso-nrel** [comment]
Fine with me to merge as-is 👍

**Comment by mikofski** [comment]
Kevin, why not add the new logo to the README as well? BTW: super cool! It looks great!

**Comment by mdeceglie** [comment]
Good idea! Opened #178

**Pull request merged**
