### PR TITLE
SRR and CODS updates

### PR DESCRIPTION
**Pull request by martin-springer**
- [ ] Code changes are covered by tests
- [ ] Code changes have been evaluated for compatibility/integration with TrendAnalysis
- [ ] New functions added to `__init__.py`
- [ ] API.rst is up to date, along with other sphinx docs pages
- [ ] Example notebooks are rerun and differences in results scrutinized
- [ ] Updated changelog

### CODE REVIEW

**Comment by martin-springer** [comment]
@noromo01 - I tried to help with the soiling.py formatting. Not sure, if I made it better or worse tough... However, all of those can be fixed easily. I can take care of that, if you like? The only one that I need your input is the last exception in soiling.py (./rdtools/soiling.py:2944:5: E722 do not use bare 'except'). What exception would you like to catch there?

**Comment by noromo01** [comment]
@martin-springer I believe I fixed the formatting issues, everything looks good to me except for that bare except. I talked to Matt about that yesterday, we are working to find a solution to that. Someone else wrote that code so we are having some difficulty figuring out how to fix that

**Comment by martin-springer** [comment]
> @martin-springer I believe I fixed the formatting issues, everything looks good to me except for that bare except. I talked to Matt about that yesterday, we are working to find a solution to that. Someone else wrote that code so we are having some difficulty figuring out how to fix that

@noromo01 - Got it. Thanks for fixing the formatting. It's looking good now. Please add your changes to the changelog under (docs\sphinx\source\changelog\pending.rst). 

@mdeceglie - Besides the one bare exception in soiling.py, this PR is ready for your review.

**Comment by noromo01** [comment]
> > @martin-springer I believe I fixed the formatting issues, everything looks good to me except for that bare except. I talked to Matt about that yesterday, we are working to find a solution to that. Someone else wrote that code so we are having some difficulty figuring out how to fix that
> 
> @noromo01 - Got it. Thanks for fixing the formatting. It's looking good now. Please add your changes to the changelog under (docs\sphinx\source\changelog\pending.rst).
> 
> @mdeceglie - Besides the one bare exception in soiling.py, this PR is ready for your review.

@martin-springer @mdeceglie Matt and I are still working out some of the kinks with the notebook testing. We got everything to look good for method='half_norm_clean' but are still trying to make sure we don't change the functionality of Matt's new methods with piecewise and negative shift detection

**Comment by mdeceglie** [comment]
Closing in favor of #432

**Pull request closed without merging**
