### PR TITLE
setup.py updated to fix bug in PACKAGE_DATA

### PR DESCRIPTION
**Pull request by cdeline**
Could someone please confirm that this install works on a Mac?  This fixes install problems on PC, but I'm not able to test other platform compatibility.

Thanks!

### CODE REVIEW

**Comment by amnag** [comment]
Hi @cdeline, I checkout out the development branch of rdtools, did a git pull and then ran:
sudo -H pip install . --upgrade. It ran successfully with the ending message that:
Successfully installed rdtools-1.1.1+6.gc9d6a1b

However, when I start a jupyter notebook, import rdtools and print out the version of rdtools
print rdtools.__version__, I get "0+untagged.209.gc9d6a1b" and not "1.1.1+6.gc9d6a1b".

**Comment by mdeceglie** [comment]
@cdeline and @dirkjordan  Can you please check this new version on your machines? I removed `package_data` from `setup.py` because the hdf file should be included already per `MANIFEST.in`, making this redundant.

**Comment by cdeline** [comment]
Installation worked for me on my PC.

**Comment by mdeceglie** [comment]
Thanks @cdeline.  
 @abshinn - do you agree with my assessment that in the previous version, the `package_data` argument in `setup.py` was redundant with `MANIFEST.in`?

**Comment by abshinn** [comment]
I agree. Here is the result of `python setup.py sdist` at the latest commit, 37348b. You can see that `rdtools/data/temperature.hdf5` is included in the distribution.

```
(rdtools) shinn@hog-staging-172~/rdtools:$ git describe --tags
1.1.0-43-gc37348b
(rdtools) shinn@hog-staging-172~/rdtools:$ python setup.py sdist
running sdist
running egg_info
writing requirements to rdtools.egg-info/requires.txt
writing rdtools.egg-info/PKG-INFO
writing top-level names to rdtools.egg-info/top_level.txt
writing dependency_links to rdtools.egg-info/dependency_links.txt
reading manifest file 'rdtools.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'rdtools.egg-info/SOURCES.txt'
running check
creating rdtools-1.1.0+43.gc37348b
creating rdtools-1.1.0+43.gc37348b/rdtools
creating rdtools-1.1.0+43.gc37348b/rdtools.egg-info
creating rdtools-1.1.0+43.gc37348b/rdtools/data
copying files to rdtools-1.1.0+43.gc37348b...
copying MANIFEST.in -> rdtools-1.1.0+43.gc37348b
copying README.md -> rdtools-1.1.0+43.gc37348b
copying setup.cfg -> rdtools-1.1.0+43.gc37348b
copying setup.py -> rdtools-1.1.0+43.gc37348b
copying versioneer.py -> rdtools-1.1.0+43.gc37348b
copying rdtools/__init__.py -> rdtools-1.1.0+43.gc37348b/rdtools
copying rdtools/_version.py -> rdtools-1.1.0+43.gc37348b/rdtools
copying rdtools/aggregation.py -> rdtools-1.1.0+43.gc37348b/rdtools
copying rdtools/clearsky_temperature.py -> rdtools-1.1.0+43.gc37348b/rdtools
copying rdtools/degradation.py -> rdtools-1.1.0+43.gc37348b/rdtools
copying rdtools/filtering.py -> rdtools-1.1.0+43.gc37348b/rdtools
copying rdtools/normalization.py -> rdtools-1.1.0+43.gc37348b/rdtools
copying rdtools.egg-info/PKG-INFO -> rdtools-1.1.0+43.gc37348b/rdtools.egg-info
copying rdtools.egg-info/SOURCES.txt -> rdtools-1.1.0+43.gc37348b/rdtools.egg-info
copying rdtools.egg-info/dependency_links.txt -> rdtools-1.1.0+43.gc37348b/rdtools.egg-info
copying rdtools.egg-info/not-zip-safe -> rdtools-1.1.0+43.gc37348b/rdtools.egg-info
copying rdtools.egg-info/requires.txt -> rdtools-1.1.0+43.gc37348b/rdtools.egg-info
copying rdtools.egg-info/top_level.txt -> rdtools-1.1.0+43.gc37348b/rdtools.egg-info
copying rdtools/data/temperature.hdf5 -> rdtools-1.1.0+43.gc37348b/rdtools/data
Writing rdtools-1.1.0+43.gc37348b/setup.cfg
UPDATING rdtools-1.1.0+43.gc37348b/rdtools/_version.py
set rdtools-1.1.0+43.gc37348b/rdtools/_version.py to '1.1.0+43.gc37348b'
Creating tar archive
removing 'rdtools-1.1.0+43.gc37348b' (and everything under it)
```

**Pull request merged**
