### PR TITLE
Automated testing and deployment along with bug fixes

### LINKED ISSUE #49: Improve unit test runner
Make use of unittests' TestSuite class for running unit tests. This will make it easier to measure test coverage.

### PR DESCRIPTION
**Pull request by mdeceglie**
Changes have been reviewed on merge into `development`. This is a final check prior to release. Please verify that you can install `rdtools` from this branch and run the notebook per the directions in the README on this branch.

closes #49 #76 #78 #79 #80 #85 #86 #92

Hopefully deployment will be automated, but we won't find out until we try!

### CODE REVIEW

**Comment by mdeceglie** [comment]
Thanks for catching that @cdeline, in this case a minor change to `notebook_requirements.txt` allows everything to work in python 2.7, so I made that change. But I don't want to commit to maintaining examples in more than one version of python. So I also added a note to the readme that examples are designed for 3.6.

Please check if this fixes the problem you ran into.

**Comment by mdeceglie** [comment]
`patsy` is an indirect requirement, but best practices for dependency management are to only put **direct** requirements in `setup.py`.  `patsy` is a dependency of `statsmodels` so it's not clear why that isn't getting installed for you when you install `statsmodels` as part of the `rdtools` install. 

I think the current state of the code complies with best practices. 
https://blog.miguelgrinberg.com/post/the-package-dependency-blues 
https://medium.com/knerd/best-practices-for-python-dependency-management-cc8d1913db82
and our dicussion of how to handle dependencies: #82

**Comment by cdeline** [comment]
OK.  Things check out in my py2.7 and py3.6 environments.  I added the indirect requirement patsy to notebooks_requirement.txt which is referenced in the example notebook.  This pull request is approved.

**Comment by mdeceglie** [comment]
Everything works on my machine too, I'll go ahead and merge.

**Pull request merged**
