### PR TITLE
add citation.cff file

### PR DESCRIPTION
**Pull request by martin-springer**
- [x] Code changes are covered by tests
- [x] Code changes have been evaluated for compatibility/integration with TrendAnalysis
- [x] New functions added to `__init__.py`
- [x] API.rst is up to date, along with other sphinx docs pages
- [x] Example notebooks are rerun and differences in results scrutinized
- [x] Updated changelog

### CODE REVIEW

**Review by mdeceglie — COMMENTED** [review]
In order to keep maintenance to a minimum, thoughts on removing version number and release date? I am ambivalent about it. If we leave it the same we should consider adding this to the PR checklist so that it doesn't get forgotten with new releases.

**Comment by martin-springer** [comment]
> In order to keep maintenance to a minimum, thoughts on removing version number and release date? I am ambivalent about it. If we leave it the same we should consider adding this to the PR checklist so that it doesn't get forgotten with new releases.

Agreed. I like to keep it simple and removed the version and release date. I've also added Quyen and Noah and updated the reference in the readme.

**Comment by martin-springer** [comment]
Looks like scikit-learn just had a new release (https://scikit-learn.org/stable/whats_new/v1.6.html#version-1-6-0) and introduced a new tag `__sklearn_tags__` that seems to be buggy and makes one of our tests fail.

**Comment by mdeceglie** [comment]
Let's use a "pending" section in the change log since 3.0.0b0 is already out.

**Review by mdeceglie — APPROVED** [review]

**Pull request merged**
