### PR TITLE
use full absolute path

### LINKED ISSUE #67: degradation notebook in docs doesn't work
* trace back message was "no module named normalization" raised on the 1st line of `rdtools/__init__.py`
* looking in `rdtools/` the file `normalization.py` does exist, but looking in `rdtools/__init__.py` shows that it was imported using a relative path, it should use an absolute path or a dot.

### PR DESCRIPTION
**Pull request by mikofski**
fixes #67

### CODE REVIEW

**Comment by mdeceglie** [comment]
@mikofski, thanks for your contribution! I have changed the pull request base to be the `development` branch. We like to keep the master branch up to date with releases (see wiki).

I'm having trouble reproducing this. Can you explain a little more about your use case? Did you install rdtools? 

If I try running the notebook without installing I get the error `ImportError: No module named rdtools`

But the changes to __init__.py don't seem to break anything. @abshinn, what do you think?

**Comment by mikofski** [comment]
Hi Mike, @jdnewmil and I both observed this using the master branch from GitHub. Here's exactly what we did step by step:
1. open an Anaconda prompt, or a CMD or Bash prompt, and activate a new conda environment for Python 3.6 called PY36.

        (root) $ conda create -n py36 python=3.6.3 numpy pandas statsmodels scipy patsy h5py pytz six
        (root) $ source activate py36  # note: `source` is only needed in BaSH
        (py36) $ conda install -c pvlib pvlib

2. clone rdtools using `git clone https://github.com/nrel/rdtools.git`
3. change into the cloned rdtools repo directory and install using `pip install .` as the [readme](https://github.com/NREL/rdtools#install-rdtools-using-pip) says.
4. change to the [`rdtools/docs`](../tree/master/docs) directory and type `jupyter notebook` at the command prompt
5. when jupyter opens in your browser click `degradation_example.ipynb`
6. go to the new tab with the degradation example notebook opened and click run all
```traceback
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-91448018e37b> in <module>()
----> 1 import rdtools

~\AppData\Local\Continuum\anaconda3\envs\py36r\lib\site-packages\rdtools\__init__.py in <module>()
----> 1 from normalization import normalize_with_sapm
      2 from normalization import normalize_with_pvwatts
      3 from normalization import irradiance_rescale
      4 from degradation import degradation_ols
      5 from degradation import degradation_classical_decomposition

ModuleNotFoundError: No module named 'normalization'
```

I also get this exact same error if I just do this:
1. open a terminal
2. install dependencies like statsmodels, pandas, numpy, scipy, pvlib, etc.
3. type `pip install rdtools`
4. start python 3.6 using `ipython`
5. try `import rdtools`

<details><pre>
(py36r) ~>pip install rdtools
Collecting rdtools
  Downloading rdtools-1.1.3.tar.gz (726kB)
    100% |████████████████████████████████| 727kB 2.4MB/s
Requirement already satisfied: numpy>=1.11.2 in ~\appdata\local\continuum\anaconda3\envs\py36r\lib\site-packages (from rdtools)
Requirement already satisfied: pandas>=0.20.3 in ~\appdata\local\continuum\anaconda3\envs\py36r\lib\site-packages (from rdtools)
Requirement already satisfied: pvlib>=0.5.0 in ~\appdata\local\continuum\anaconda3\envs\py36r\lib\site-packages (from rdtools)
Requirement already satisfied: statsmodels>=0.8.0 in ~\appdata\local\continuum\anaconda3\envs\py36r\lib\site-packages (from rdtools)
Requirement already satisfied: scipy>=0.19.1 in ~\appdata\local\continuum\anaconda3\envs\py36r\lib\site-packages (from rdtools)
Requirement already satisfied: patsy>=0.4.1 in ~\appdata\local\continuum\anaconda3\envs\py36r\lib\site-packages (from rdtools)
Requirement already satisfied: h5py>=2.7.1 in ~\appdata\local\continuum\anaconda3\envs\py36r\lib\site-packages (from rdtools)
Requirement already satisfied: pytz in ~\appdata\local\continuum\anaconda3\envs\py36r\lib\site-packages (from rdtools)
Requirement already satisfied: six in ~\appdata\local\continuum\anaconda3\envs\py36r\lib\site-packages (from rdtools)
Requirement already satisfied: python-dateutil>=2 in ~\appdata\local\continuum\anaconda3\envs\py36r\lib\site-packages (from pandas>=0.20.3->rdtools)
Building wheels for collected packages: rdtools
  Running setup.py bdist_wheel for rdtools ... done
  Stored in directory: ~\AppData\Local\pip\Cache\wheels\3d\9a\9b\24b3ef4c80e47415b4070b1d1e299f0063ab075b7a03a198ee
Successfully built rdtools
Installing collected packages: rdtools
Successfully installed rdtools-1.1.3
</pre><pre>
(py36r) ~>ipython
Python 3.6.3 |Anaconda, Inc.| (default, Nov  8 2017, 15:10:56) [MSC v.1900 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.
</pre><pre>
>>> import rdtools
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-91448018e37b> in <module>()
----> 1 import rdtools
</pre><pre>
~\AppData\Local\Continuum\anaconda3\envs\py36r\lib\site-packages\rdtools\__init__.py in <module>()
----> 1 from normalization import normalize_with_sapm
      2 from normalization import normalize_with_pvwatts
      3 from normalization import irradiance_rescale
      4 from degradation import degradation_ols
      5 from degradation import degradation_classical_decomposition
</pre><pre>
ModuleNotFoundError: No module named 'normalization'
</pre></details>

**Comment by mdeceglie** [comment]
Thanks for adding those details. We don't yet support python 3 (issue #56), which could explain why I couldn't reproduce it in python 2.7. 

This is documented in `CLASSIFIERS` in `setup.py` but we should make it more prominent that there is no python 3 support yet in the readme. I will open an issue and address it in the near future.

**Comment by mikofski** [comment]
okay, thanks that explains it. Too bad pip isn't smart enough to block this installation.

* I think if you were to [release it as a wheel built with Python-2](https://packaging.python.org/tutorials/distributing-packages/#wheels) then you wouldn't have this issue.

* Also it appears that if you add [`python_requires='<3'`](https://packaging.python.org/tutorials/distributing-packages/#python-requires) to your [`setup.py`](../blob/master/setup.py) then it should also restrict it to Python-2 maybe?

* IMHO highlights a potential issue in rdtools. Python 3 won't tolerate relative imports which are ambiguous. _IE_: Did you mean to import `normalization` from the `PYTHONPATH` or `normalization.py` that is relative to `__init__.py`. You and I both know, but if there _is_ a package named `normalization` that you installed using pip or conda into your `site-packages` folder, then you will have a conflict. See [pep8 on imports](http://pep8.org/#imports) and [pep-328 on relative imports](https://www.python.org/dev/peps/pep-0328/). According to [Guido's Decision](https://www.python.org/dev/peps/pep-0328/#guido-s-decision) we should use dots:

        from .normalization from import normalize_with_sapm

    Note the **dot** prepended to `normalization` signifying a _relative_ import, but to me this violates the [Zen of Python](https://www.python.org/dev/peps/pep-0020/)

    >Explicit is better than implicit.

    Therefore I prefer to use the full namespace dotted path to the desired module which IMO is unambiguos

        from rdtools.normalization from import normalize_with_sapm

    which must work since `import rdtools` works

**Pull request merged**
