### PR TITLE
Update ReadTheDocs configuration

### PR DESCRIPTION
**Pull request by kandersolar**
- ~Code changes are covered by tests~
- ~Code changes have been evaluated for compatibility/integration with TrendAnalysis~
- ~New functions added to `__init__.py`~
- ~API.rst is up to date, along with other sphinx docs pages~
- ~Example notebooks are rerun and differences in results scrutinized~
- [x] Updated changelog

ReadTheDocs is requiring a change in the configuration file (see this [failed build](https://readthedocs.org/projects/rdtools/builds/22114871/)):

> Your builds will stop working soon!
> "build.image" config key is deprecated and it will be removed soon. [Read our blog post to know how to migrate to new key "build.os"](https://blog.readthedocs.com/use-build-os-config/) and ensure your project continues building successfully.

This PR makes the necessary configuration updates.

### CODE REVIEW

**Comment by mdeceglie** [comment]
I was able to resolve one of the bugs with our test suite and pandas 2.1. The other seems to be a pandas issue https://github.com/pandas-dev/pandas/issues/55794

**Comment by mdeceglie** [comment]
Shall we push this through and confine the requirements to pandas<2.1 while we await a fix on the pandas side?

**Comment by kandersolar** [comment]
Makes sense to me to go ahead with merging this and track the pandas issue separately!

**Comment by mdeceglie** [comment]
@cdeline @martin-springer I agree with @kandersolar  that we should push this through for now. Would one of you be able to review this?

**Review by cdeline — APPROVED** [review]
LGTM!

**Comment by mdeceglie** [comment]
The failing notebook checks are related to a Datahub error affecting our example data. I'm confident the ntoebooks haven't changed with this one, so pushing it through.

**Pull request merged**
