### PR TITLE
Update requirements files

### PR DESCRIPTION
**Pull request by kanderso-nrel**
- ~Code changes are covered by tests~
- ~New functions added to `__init__.py`~
- ~API.rst is up to date, along with other sphinx docs pages~
- [x] Example notebooks are rerun and differences in results scrutinized
- [x] Updated changelog

This PR does three things:

1) Updates a few dependencies per dependabot's recommendation (#267, #268)
2) Adds a bunch of missing indirect dependencies to our two requirements files
3) Fixes an incompatibility between numpy and certain versions of windows (see https://developercommunity.visualstudio.com/t/fmod-after-an-update-to-windows-2004-is-causing-a/1207405)

Updating requirements files is not necessarily trivial to do correctly, so I made a little helper script to help with item 2 next time we have to do it: https://github.com/NREL/rdtools/wiki/Updating-Requirements-Files

### CODE REVIEW

**Comment by cdeline** [comment]
Sorry, jumped the gun and merged #267 for jinja2.  Should I undo it?

**Comment by kanderso-nrel** [comment]
No worries, I'll just fix the merge conflicts for #267 and #268 on this one.

**Review by cdeline — APPROVED** [review]
Looks good, thanks for working through these dependencies

**Comment by mdeceglie** [comment]
LGTM

**Pull request merged**
