### PR TITLE
support Python 3

### LINKED ISSUE #56: Add python 3 support

### PR DESCRIPTION
**Pull request by mikofski**
* closes #56 and addresses #67, #68, and #70 
* running `2to3 rdtools/` shows the only issue is the relative imports already addressed in #67 so merge #68 
* running `2to3 tests/` shows only Python-2 style print commands, so rerun

        $ 2to3 -f print -w -n tests/

    to replace print command with print calls using parentheses, works in both Python 2 and 3
* search for any Python-2 iterators like `xrange`, or `iteritems()`, etc., and none found
* all tests are passing!
```
$ pytest
============================= test session starts ==============================
platform darwin -- Python 3.6.4, pytest-3.3.0, py-1.5.2, pluggy-0.6.0
rootdir: /Users/markmikofski/Projects/rdtools, inifile:
plugins: hypothesis-3.38.5
collected 10 items                                                             

tests/aggregation_test.py ..                                             [ 20%]
tests/clearsky_temperature_test.py .                                     [ 30%]
tests/degradation_test.py ...                                            [ 60%]
tests/normalization_pvwatts_test.py ..                                   [ 80%]
tests/normalization_sapm_test.py ..                                      [100%]

========================== 10 passed in 25.77 seconds ==========================
```

### CODE REVIEW

**Comment by mikofski** [comment]
development branch also passing
```
$ pytest
============================= test session starts ==============================
platform darwin -- Python 3.6.4, pytest-3.3.0, py-1.5.2, pluggy-0.6.0
rootdir: /Users/markmikofski/Projects/rdtools, inifile:
plugins: hypothesis-3.38.5
collected 7 items                                                              

tests/aggregation_test.py ..                                             [ 28%]
tests/clearsky_temperature_test.py .                                     [ 42%]
tests/normalization_pvwatts_test.py ..                                   [ 71%]
tests/normalization_sapm_test.py ..                                      [100%]

=========================== 7 passed in 2.53 seconds ===========================
```

**Comment by mikofski** [comment]
FYI: AFAICT `rdtools` should work fine in Python-3 as is, as long as you don't run the tests and you merge #68. But the tests had `print` statements, hence this PR.

**Comment by mdeceglie** [comment]
There are a few changes I'd like to suggest for the example notebook to make it work smoothly. @mikofski, would you mind providing push permissions to the PR according to: https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/ ?

**Comment by mdeceglie** [comment]
One of the problems is related to special characters in renaming the columns from the sample file.  The current version works in python 2 but not 3:
```
df = df.rename(columns = {
    '12 BP Solar - Active Power (kW)':'power',
    '12 BP Solar - Wind Speed (m/s)': 'wind',
    '12 BP Solar - Weather Temperature Celsius (\xc2\xb0C)': 'Tamb',
    '12 BP Solar - Global Horizontal Radiation (W/m\xc2\xb2)': 'ghi',
    '12 BP Solar - Diffuse Horizontal Radiation (W/m\xc2\xb2)': 'dhi'
})
```
For python 3, it works to use:
```
df = df.rename(columns = {
    '12 BP Solar - Active Power (kW)':'power',
    '12 BP Solar - Wind Speed (m/s)': 'wind',
    '12 BP Solar - Weather Temperature Celsius (\xb0C)': 'Tamb',
    '12 BP Solar - Global Horizontal Radiation (W/m\xb2)': 'ghi',
    '12 BP Solar - Diffuse Horizontal Radiation (W/m\xb2)': 'dhi'
})
```
But neither works for both. The best I've come up with that works for both is:
```
dhi_str = [x for x in df.columns.values if 'Diffuse Horizontal Radiation' in x][0]
ghi_str = [x for x in df.columns.values if 'Global Horizontal Radiation' in x][0]
Tamb_str = [x for x in df.columns.values if 'Weather Temperature Celsius' in x][0]

df = df.rename(columns = {
    '12 BP Solar - Active Power (kW)':'power',
    '12 BP Solar - Wind Speed (m/s)': 'wind',
    Tamb_str: 'Tamb',
    ghi_str: 'ghi',
    dhi_str: 'dhi'
})
```
But I am open to other suggestions if anyone is aware of a better/cleaner way.

**Comment by mikofski** [comment]
Sorry, I didn't see these issues. Usually the best way to resolve string compatibility issues between Python 2 and Python 3 is to use unicode. Eg: `blah`.decode('utf-8')` Let me take a crack. Also, I'll flip the maintainer editing switch so you can make changes directly to the PR.

**Comment by mdeceglie** [comment]
Great, thank you. If you come up with something for the string compatibility please include it in a comment here, rather than changing the notebook directly. I will push an updated notebook, and I would like to avoid resolving conflicts on a jupyter notebook...

**Comment by mikofski** [comment]
* BTW: the "allow edits from maintainers" switch is already enabled
allow_edits_from_maintainers
* I fixed the decoding error for the dataframe column names
* I also updated two print statements to be compatible with Python-3
* and I changed the bins in histograms to use integer divide
* works for both Python-2.7 and Python-3.6 now
    - [degradation_example_py3.pdf](https://github.com/NREL/rdtools/files/1778068/degradation_example_py3.pdf)
    - [degradation_example_py2.pdf](https://github.com/NREL/rdtools/files/1778077/degradation_example_py2.pdf)

* the [Python-future](http://python-future.org/compatible_idioms.html) package and website is sometimes helpful for resolving Python 2/3 compatibility issues

**Comment by mikofski** [comment]
oops too late

**Comment by mikofski** [comment]
but you can use [nbdime](https://nbdime.readthedocs.io/en/stable/) to diff notebooks

**Comment by mikofski** [comment]
I made my changes directly into the `.ipynb` file to minimize notebooks changes

**Comment by mdeceglie** [comment]
Looks great, you caught the same changes that I had. Thanks for the tip about nbdime, and more importantly for the contribution to RdTools. I will merge this, close PR #68, and update the issue tracker.

**Pull request merged**
