### PR TITLE
Cherry-pick the plotting module out of the system analysis branch

### PR DESCRIPTION
**Pull request by kanderso-nrel**
This cherry-picks out the plotting module present in 2.0.0-alpha and then cleans up docstrings and incorporates them into the sphinx API reference.  Marking as a draft for now because I want to make sure I didn't miss any commits.

### CODE REVIEW

**Comment by mdeceglie** [comment]
@cdeline proposed a change to the bin counts in `degradation_summary_plots()` in #133, Still haven't reached consensus on that.

**Comment by mdeceglie** [comment]
Looks ready to me as long as everyone is comfortable with the default bin behavior.

**Comment by kanderso-nrel** [comment]
Next step is to extend tests to exercise all the keyword arguments.

**Comment by kanderso-nrel** [comment]
@mdeceglie @cdeline thoughts on this test approach?

**Comment by kanderso-nrel** [comment]
> so that we get more info about which assert statement failed and why

It seems preferable to have the context of a failure be obvious without us having to put in explanations, so I did what I should have done anyway and moved each assert into its own test function.  Here's the output for a (contrived) failure -- do you still think that custom explanations would be helpful?  

```
def test_soiling_monte_carlo_plot_kwargs(soiling_normalized_daily, soiling_info):
        # test kwargs
        kwargs = dict(
            point_alpha=0.1,
            profile_alpha=0.4,
            ymin=0,
            ymax=1,
            profiles=5,
            point_color='k',
            profile_color='b',
        )
        result = soiling_monte_carlo_plot(soiling_info, soiling_normalized_daily,
                                          **kwargs)
        result = None
>       assert isinstance(result, plt.Figure)
E       AssertionError: assert False
E        +  where False = isinstance(None, <class 'matplotlib.figure.Figure'>)
E        +    where <class 'matplotlib.figure.Figure'> = plt.Figure

rdtools\test\plotting_test.py:122: AssertionError
```

**Comment by kanderso-nrel** [comment]
Also, is Travis showing up for anyone on this PR? The "Checks" section is empty for me.  It's definitely keeping track of this PR: https://travis-ci.org/NREL/rdtools/requests?utm_medium=notification&utm_source=github_status

**Comment by mdeceglie** [comment]
Looks like `test_degradation_summary_plots()` still has two asserts.

**Comment by mdeceglie** [comment]
I won't die on this hill, but how much will our future selves love us if we did something like this? e.g. in `test_soiling_monte_carlo_plot()` 
```
result_type = type(result)
assert isinstance(result, plt.Figure), f'soiling_monte_carlo_plot() returned a {result_type} instead of a matplotlib Figure'
```

**Comment by kanderso-nrel** [comment]
Note to future RdTools developers:  you better appreciate this.

Example failure output with that change.  Acceptable? 

```
__________________________ test_degradation_summary_plots_kwargs __________________________

degradation_info = (2017-01-01 00:00:00+00:00    0.900000
2017-01-02 00:00:00+00:00    0.900003
2017-01-03 00:00:00+00:00    0.900035
201...yoy, Length: 731, dtype: float64, 'exceedance_level': -0.5009634348652536, 'renormalizing_factor': 0.9975627132285956})

    def test_degradation_summary_plots_kwargs(degradation_info):
        power, yoy_rd, yoy_ci, yoy_info = degradation_info

        # test kwargs
        kwargs = dict(
            hist_xmin=-1,
            hist_xmax=1,
            bins=100,
            scatter_ymin=0,
            scatter_ymax=1,
            plot_color='g',
            summary_title='test',
            scatter_alpha=1.0,
        )
        result = degradation_summary_plots(yoy_rd, yoy_ci, yoy_info, power,
                                           **kwargs)
        result = None
>       assert_isinstance(result, plt.Figure)

rdtools\test\plotting_test.py:88:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

obj = None, klass = <class 'matplotlib.figure.Figure'>

    def assert_isinstance(obj, klass):
>       assert isinstance(obj, klass), f'got {type(obj)}, expected {klass}'
E       AssertionError: got <class 'NoneType'>, expected <class 'matplotlib.figure.Figure'>
E       assert False
E        +  where False = isinstance(None, <class 'matplotlib.figure.Figure'>)

rdtools\test\plotting_test.py:24: AssertionError
```

**Comment by mdeceglie** [comment]
Looks good. Notwithstanding the travis CI mystery, it isn't showing for me either...

**Comment by cdeline** [comment]
My original intent was to merge this behavior into model_chains which hasn't happened yet.  Doing that now.

**Pull request merged**
