### PR TITLE
Plotting module

### PR DESCRIPTION
**Pull request by amnag**
Pull request to merge the plotting_module branch with the master branch

### CODE REVIEW

**Comment by mdeceglie** [comment]
@amnag Thank you for this contribution.

I'm Changing the PR base to `development` in accordance with our workflow (more details: https://github.com/NREL/rdtools/wiki).

I'd like to focus first on getting a new release out. Then we will consider this PR in more detail.

**Comment by amnag** [comment]
@mdeceglie, you are welcome !

**Comment by cdeline** [comment]
I'm going to re-base this branch on development and push-force back up because it's so old.  Please let me know if you're actively working on this branch, which is unlikely.

**Comment by cdeline** [comment]
This is now set up with plotting functions that return the (fig,ax) of the plot that is printed.

**Comment by mdeceglie** [comment]
A couple of points for discussion:

1. I suggest we abandon xyplot() and xy2plot(). There's not much rdtools-specific value added over the functionality of matplotlib or the already existing pandas wrappers.

2. The histogram currently shows all the YOY changes, which is a very wide distribution and doesn't match with the bootstrapped confidence interval that we report. In the example it's just an extremely broad distribution from -20 to + 20 %.year, which doesn't tell me much. I'm concerned this may be confusing to people. Should we dispense with the histogram? Make it a histogram of bootstrap realizations? Something else?

**Comment by cdeline** [comment]
This is stale, and appears to be picked up in  the modelchains branch in 3350b314045b8716034f1dfd11421586c60f2df8.  Closing this and deleting the plotting_module branch.

**Pull request closed without merging**
