### PR TITLE
set lw to 0 in plotting.degradation_summary_plots

### PR DESCRIPTION
**Pull request by martin-springer**
- [x] Code changes are covered by tests
- [x] Code changes have been evaluated for compatibility/integration with TrendAnalysis
- [x] New functions added to `__init__.py`
- [x] API.rst is up to date, along with other sphinx docs pages
- [x] Example notebooks are rerun and differences in results scrutinized
- [x] Updated changelog

### CODE REVIEW

**Review by mdeceglie — CHANGES_REQUESTED** [review]
This looks good, but please re-run and commit affected notebooks

**Comment by mdeceglie** [comment]
Please also re-run the two trend analysis notebooks, then we should be good to go. Thanks!

**Comment by mdeceglie** [comment]
Let's use a "pending" section in the change log since 3.0.0b0 is already out.

**Comment by martin-springer** [comment]
> Let's use a "pending" section in the change log since 3.0.0b0 is already out.

Done.

**Review by mdeceglie — APPROVED** [review]

**Pull request merged**
